### ISSUE TITLE
Do we need package 'node-fetch'?

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#11]
Perhaps [`http.get()`](https://nodejs.org/dist/latest-v6.x/docs/api/http.html#http_http_get_options_callback) or `http.request()` suffice?

**Comment by iherman** [comment]
Maybe. Probably.

The reason I want for `fetch` were because that seems to be where the community is going these days in Javascript land (if my understanding is correct). Also, fetch is inherently based on Promises, whereas one has to put an extra layer on top of `http` to use Promises; on the other hand, I believe using Promises indeed makes the code readable than using callbacks. 

(B.t.w., I have spent some time to see how `wait`-`async` would be used for the code and it would indeed make it even cleaner and more readable. I is not part of Node 6, hence I did not use it, but we may want to so if we upgrade to Node 8). And that stuff is also heavily Promise-dependent...)

**Comment by tripu** [comment]
I generally prefer to use native modules when possible; for portability and security, and to keep dependencies at a minimum. (I'm not concerned about using callbacks instead of promises. Anyway, in this case I rewrote that `GET` part using `http.get()` in roughly the same number of lines, resolving that promise without further issues; see below.)

However, in this particular case I see there are advantages to using `node-fetch`:

* HTTP and HTTPS are handled by two separate modules in Node.js 8; that is silly and would force us [to examine the protocol of each URL to decide which one to use](https://stackoverflow.com/a/38465918/45758).
* `node-fetch` takes care of redirects and other cases, but the native modules don't.

Anyway, for future reference, this would be roughly the equivalent code, replacing [`io.js#L31-L45`](https://github.com/w3c/scribejs/blob/master/io.js#L31-L45):

```javascript
https.get(conf.input, (res) => {
    if (200 === res.statusCode) {
        let document = '';
        res.on('data', (data) => document += data);
        res.on('end', () => resolve(document));
    } else
        throw new Error(`HTTP response ${res.statusCode}: ${res}`);
}).on('error', (err) => throw new Error(`${err}`));
```
