### ISSUE TITLE
Do we need "CGI/protocol.js"?

### ISSUE THREAD

**Issue by tripu** [w3c/scribejs#13]
Explore existing npm packages: [`https://www.npmjs.com/search?q=cgi`](https://www.npmjs.com/search?q=cgi).

**Comment by tripu** [comment]
Perhaps [`node-fastcgi`](https://www.npmjs.com/package/node-fastcgi).

**Comment by iherman** [comment]
I looked at it and... I am now more in the “ain't broken, don’t fix it!” mood.

What I have done is a minimal layer for what I need. The `fast-cgi` module has been written for some higher level goals, namely to set up a server that would react on various incoming methods (`scribejs` doesn't operate in server mode). The documentation, as usual, is almost non-existent, more exactly it refers to a document written for another package 20 years ago, for C (or is the documentation for IDL?), etc. All translation from that document to the Javascript equivalent must be done by… feeling, because there is no documentation.

It would be a lot of work, the result would be, in my view, error-prone, for no good reason. 

My proposal is to close this issue with no further action.
